
#General settings
[General]
	#Chance of a Lunar Event happening when night falls [Default: 0.4]
	#Range: 0.0 ~ 1.0
	lunarEventChance = 0.2

#Event settings
[Events]
	#Weight of the Blood Moon Event [Default: 60]
	#Range: 0 ~ 100
	bloodMoonWeight = 60
	#Weight of the Crimson Moon Event [Default: 20]
	#Range: 0 ~ 100
	crimsonMoonWeight = 20
	#Weight of the Miner Moon Event [Default: 40]
	#Range: 0 ~ 100
	minerMoonWeight = 35
	#Weight of the White Moon Event [Default: 10]
	#Range: 0 ~ 100
	whiteMoonWeight = 10
	#Weight of the Tiny Moon Event [Default: 10]
	#Range: 0 ~ 100
	tinyMoonWeight = 10
	#Weight of the Big Moon Event [Default: 10]
	#Range: 0 ~ 100
	bigMoonWeight = 10
	#Weight of the Big Moon Event [Default: 5]
	#Range: 0 ~ 100
	badOmenMoonWeight = 5
	#Weight of the Hero Moon Event [Default: 5]
	#Range: 0 ~ 100
	heroMoonWeight = 5
	#Weight of the Eclipse Moon Event [Default: 2]
	#Range: 0 ~ 100
	eclipseMoonWeight = 1

#Crimson Replacement settings
[Crimson]
	#List of entities to replace during the Crimson Moon Event [Example: "minecraft:zombie,minecraft:zombified_piglin"]
	crimsonReplacements = ["minecraft:zombie,minecraft:zombified_piglin", "minecraft:husk,realmrpg_wyrms:red_wyrm", "minecraft:drowned,minecraft:zombified_piglin", "minecraft:skeleton,minecraft:wither_skeleton", "minecraft:creeper,netheroverhaul:warped_shroomling,", "minecraft:slime,minecraft:magma_cube", "minecraft:spider,pots_and_mimics:nether_pot_crab", "rats:rat,rats:demon_rat", "enderzoology:fallen_knight,netheroverhaul:basalt_snail", "enderzoology:enderminy,netheroverhaul:crimson_shroomling"]

